# Generated by Django 2.1.4 on 2019-03-28 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Javagochi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=256)),
                ('current_health', models.IntegerField()),
                ('current_hunger', models.IntegerField()),
                ('current_cold', models.IntegerField()),
                ('current_hot', models.IntegerField()),
                ('current_age', models.IntegerField()),
                ('current_level', models.IntegerField()),
                ('current_experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JavagochiBase',
            fields=[
                ('image', models.ImageField(upload_to='javagochi_bases/')),
                ('race', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('max_health', models.IntegerField()),
                ('max_hunger', models.IntegerField()),
                ('max_cold', models.IntegerField()),
                ('max_hot', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('cost', models.FloatField()),
                ('min_user_level', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='javagochi',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='javagochi.JavagochiBase'),
        ),
    ]
