# Generated by Django 2.1.7 on 2019-10-28 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Javagochi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('current_health', models.IntegerField()),
                ('current_hunger', models.IntegerField()),
                ('current_cold', models.IntegerField()),
                ('current_hot', models.IntegerField()),
                ('current_age', models.IntegerField(default=1)),
                ('current_level', models.IntegerField(default=1)),
                ('current_experience', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JavagochiBase',
            fields=[
                ('image', models.ImageField(upload_to='javagochi_bases/')),
                ('race', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('strength', models.IntegerField(default=50)),
                ('max_health', models.IntegerField()),
                ('max_hunger', models.IntegerField()),
                ('max_cold', models.IntegerField()),
                ('max_hot', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('cost', models.FloatField()),
                ('min_user_level', models.IntegerField()),
                ('exp_on_buy', models.IntegerField()),
                ('evolves_at', models.IntegerField(blank=True, null=True)),
                ('evolves_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='javagochi.JavagochiBase')),
            ],
        ),
        migrations.CreateModel(
            name='JavagochiExpMap',
            fields=[
                ('level', models.IntegerField(primary_key=True, serialize=False)),
                ('exp_for_next_level', models.IntegerField()),
                ('coins_reward', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JavagochiType',
            fields=[
                ('type', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('weakness', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='javagochibase',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='javagochi.JavagochiType'),
        ),
        migrations.AddField(
            model_name='javagochi',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='javagochi.JavagochiBase'),
        ),
    ]
