# Generated by Django 2.1.4 on 2019-03-30 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('javagochi', '0002_javagochi_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javagochi',
            name='owner',
            field=models.ForeignKey(default=users.models.CustomUser, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
