# Generated by Django 2.1.4 on 2019-03-30 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('javagochi', '0004_auto_20190330_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javagochi',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
