# Generated by Django 2.1.4 on 2019-04-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('javagochi', '0007_javagochibase_exp_on_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='JavagochiExpMap',
            fields=[
                ('level', models.IntegerField(primary_key=True, serialize=False)),
                ('exp_for_next_level', models.IntegerField()),
                ('coins_reward', models.IntegerField()),
            ],
        ),
    ]
