# Generated by Django 2.1.4 on 2019-04-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('javagochi', '0008_javagochiexpmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javagochi',
            name='current_age',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='javagochi',
            name='current_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='javagochi',
            name='current_level',
            field=models.IntegerField(default=1),
        ),
    ]
