# Generated by Django 2.1.4 on 2019-04-13 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('javagochi', '0009_auto_20190409_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='javagochibase',
            name='evolves_at',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='javagochibase',
            name='evolves_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='javagochi.JavagochiBase'),
        ),
    ]
