# Generated by Django 2.1.7 on 2019-04-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('javagochi', '0010_auto_20190413_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='javagochibase',
            name='strength',
            field=models.IntegerField(default=50),
        ),
    ]
