# Generated by Django 2.2 on 2019-04-29 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('javagochi', '0011_javagochibase_strength'),
    ]

    operations = [
        migrations.CreateModel(
            name='JavagochiType',
            fields=[
                ('type', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('weakness', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='javagochibase',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='javagochi.JavagochiType'),
        ),
    ]
