# Generated by Django 2.1.4 on 2019-04-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpMap',
            fields=[
                ('level', models.IntegerField(primary_key=True, serialize=False)),
                ('exp_for_next_level', models.IntegerField()),
            ],
        ),
    ]
