version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/javagochi-server-master/
permissions:
  - object: /var/www/javagochi-server-master/
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 60
      runas: root
