# Generated by Django 2.1.7 on 2019-10-28 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('javagochi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('started', models.DateField(auto_now=True)),
                ('interested_into', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='javagochi.JavagochiBase')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='javagochi.Javagochi')),
            ],
        ),
    ]
