# Generated by Django 2.1.4 on 2019-04-15 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('javagochi', '0010_auto_20190413_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested_into', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='javagochi.JavagochiBase')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='javagochi.Javagochi')),
            ],
        ),
    ]
