# Generated by Django 2.1.4 on 2019-04-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseitem',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
