#!/bin/bash
cd /var/www/javagochi-server-master/
sudo pip install -r requirements
sudo python3 manage.py makemigrations
sudo python3 manage.py migrate
sudo python3 manage.py runserver > /dev/null 2> /dev/null < /dev/null &
#!service httpd start
